spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://test-server:15433/content
    username: db-username
    password: db-password
    hikari:
      connection-test-query: "SELECT 1"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform:  icu.lowcoder.spring.cloud.content.helper.JsonbPostgresDialect

security:
  oauth2:
    resource:
      token-info-uri: http://gateway:8080/uac/oauth/check_token

icu:
  lowcoder:
    spring:
      commons:
        feign:
          service-authenticate:
            client-id: service-client
            client-secret: "<service-client-secret>"
            access-token-uri: http://gateway:8080/uac/oauth/token
            grant-type: client_credentials
            client-authentication-scheme: form