spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://test-db:5433/config-repo
    username: db-username
    password: db-password
    hikari:
      connection-test-query: "SELECT 1"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        
server:
  port: 19084

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:18080/uac/oauth/check_token