spring:
  cloud:
    gateway:
      routes:
        # commons org service
        - id: org_service
          uri: lb://org-service
          predicates:
            - Path=/org/**
          filters:
            - StripPrefix=1
        # bridge we chat
        - id: we_chat_bridge_service
          uri: lb://we-chat-bridge-service
          predicates:
            - Path=/bridge/we-chat/**
          filters:
            - StripPrefix=2
        # commons org service
        - id: db_config_service
          uri: lb://db-config-service
          predicates:
            - Path=/db-config/**
          filters:
            - StripPrefix=1
        # content service
        - id: content_service
          uri: lb://content-service
          predicates:
            - Path=/content/**
          filters:
            - StripPrefix=1