spring:
  rabbitmq:
    host: rabbitmq
  redis:
    host: redis
  datasource:
    hikari:
      connection-timeout: 60000
      max-lifetime: 600000
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100

logging:
  file:
    name: "/var/logs/lowcoder/cloud/${spring.application.name:spring}.log"
  level:
    org.springframework.cloud.commons.util.InetUtils: trace

icu:
  lowcoder:
    spring:
      commons:
        exception:
          print-stack-trace: false
          show-detail: false
