eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVERS}

  environment: test

icu:
  lowcoder:
    spring:
      commons:
        management:
          security:
            enabled: true

logging:
  file:
    name: /var/logs/lowcoder/cloud/${spring.application.name:spring}.log

spring:
  rabbitmq:
    host: 172.16.4.198
    port: 15672